### ISSUE TITLE
Tidak Bisa Kirim Ke Email

### ISSUE THREAD

**Issue by ProjectGear** [cahyadsn/papi#1]
Apakah Hasil PapiKostik ini bisa dikirim khusus ke HR Perusahaan ? Tanpa dikirim ke user tes

**Comment by cahyadsn** [comment]
pengiriman hasil ke email tertentu (contoh: HR Perusahaan) bisa dilakukan dengan mengarahkan tujuan pengiriman hasil ke email tersebut. Pengiriman hasil test via email ke email tertentu  saat ini tidak termasuk dalam repo public di github ini, hanya ada di versi demo

**Comment by ProjectGear** [comment]
berbayar pa ?
